In [1]:
print("Hello World !")

Hello World !


In [8]:
import numpy as np

arr=np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [12]:
zero = np.zeros((2,3))
zero


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
one = np.ones((4,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
random = np.random.rand(2,3)
random

array([[0.81783841, 0.58661259, 0.26587653],
       [0.01362742, 0.79967962, 0.21366265]])

In [17]:
arr.shape

(5,)

In [18]:
matrix.shape


(2, 2)

In [19]:
matrix.ndim

2

In [21]:
matrix.size

4

In [22]:
matrix.dtype

dtype('int32')

In [25]:
ar1=np.array([1,2,3,4])
ar2=np.array([3,4,21,3])

print(ar1+ar2)
print(ar1*ar2)


[ 4  6 24  7]
[ 3  8 63 12]


In [28]:
#matrix multiplication 
mrx1=np.array([[1,2],[2,3]])
mrx2=np.array([[6,2],[2,8]])

print(np.dot(mrx1,mrx2))


[[10 18]
 [18 28]]


In [34]:
print(np.sum(ar1))
print(np.mean(ar2))
print(np.max(ar1))

10
7.75
4


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [39]:
arrs = np.array([1, 2, 3, 4, 5, 6])
print(arrs+10) # Adds 10 to each element.

print(arrs[arrs<5])
arrs>5

[11 12 13 14 15 16]
[1 2 3 4]


array([False, False, False, False, False,  True])

np.arange(start, stop, step): Create arrays with a range of values.
np.linspace(start, stop, num): Create evenly spaced values.
np.concatenate((arr1, arr2)): Combine arrays.
np.transpose(matrix): Transpose a matrix.

In [40]:
# Original 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2x3 array
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [41]:
#Use -1 for automatic dimension inference
reshaped = arr.reshape(3, -1)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
#ravel() is used to flatten a multidimensional array into a 1D array.
#It provides a view (not a copy) of the original array, so changes affect the original.

matrixA = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array
flattened = matrixA.ravel()
print(flattened)


[1 2 3 4 5 6]


In [43]:
transposed = matrixA.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked = np.hstack((arr1, arr2))
print(stacked)

[1 2 3 4 5 6]


In [51]:
stacked = np.vstack((arr1, arr2))
print(stacked)


[[1 2 3]
 [4 5 6]]


In [50]:
stacked = np.dstack((arr1, arr2))
print(stacked)


[[[1 4]
  [2 5]
  [3 6]]]


In [52]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
split = np.hsplit(arr, 2)
print(split)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [53]:
split = np.vsplit(arr, 2)
print(split)


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])
split = np.split(arr, 3)  # Split into 3 equal parts
print(split)


[array([1, 2]), array([3, 4]), array([5, 6])]
